jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required permission

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install
        run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  # Required permission
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B64CAB5ECBAE457D80717831D4C836D3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3BC8CFA69CF4439E9D69B67CC9727823 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7A661C15ACB44FB5882D45D96EAC2D7D }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chess-app'
          slot-name: 'Production'
          package: .
